Distribution of agents by percentage
JuPedSim/jpscore pull request #1052
Opened 2022-11-09 13:37 UTC by ChristianHirt

Adds new Methods for Agent distribution:

distribute by percent and distribute till full inside a polygon

todo:

- [ ] tests for Methods

2022-12-07 09:01 UTC, JetteSchumann requested changes

2022-12-07 14:00 UTC, ChristianHirt commented on python_modules/jupedsim/jupedsim/distributions.py
> +    samples = distribute_til_full(polygon=polygon, distance_to_agents=distance_to_agents,
resolved as discussed

2022-12-08 12:27 UTC, ChristianHirt commented on python_modules/jupedsim/jupedsim/distributions_app.py
> +            st.text('Below should be a plot')
added

2022-12-08 12:27 UTC, ChristianHirt commented on python_modules/jupedsim/jupedsim/distributions_app.py
> +                "you can enter how many tries there should be to\n"
removed

2022-12-08 12:27 UTC, ChristianHirt commented on python_modules/jupedsim/jupedsim/distributions_app.py
> +                "distributes agents all over the polygon\n"
instructions rewritten

2022-12-08 12:28 UTC, ChristianHirt commented on python_modules/jupedsim/jupedsim/distributions.py
readme updated

2022-12-08 12:29 UTC, ChristianHirt commented on python_modules/jupedsim/jupedsim/distributions_app.py
> +                "General settings can be made in the left sidebar")
general instructions are explained in sidebar
specific informations are explained after selection of distribution type

2022-12-14 11:24 UTC, JetteSchumann requested changes

2022-12-14 11:30 UTC, JetteSchumann approved these changes

2022-12-14 11:55 UTC, merged