Add Skript to convert AKNZ geometry to WKT
JuPedSim/jpscore pull request #1087
Opened 2023-03-31 09:22 UTC by ChristianHirt

Fixes #1071

2023-04-18 06:00 UTC, ChristianHirt commented
![aknz_difference](https://user-images.githubusercontent.com/92570899/232684313-06983c64-bd4c-45c1-805d-52444549c60b.png)
This is the difference between the arrival and evacuation geometry.
you can see that it differs mainly in two new large emergency exits. But also a path on the left side is now a bit longer. Also inconspicuous but different are some coordinates above the path on the left side. these are very difficult to see here, but here some coordinates differ minimally.

2023-04-21 13:17 UTC, Ozaq requested changes
@ChristianHirt Please add some doc to the script, really just some high level description what this does and what it is used for. Just a couple of sentences will do. Otherwise this is good to go.

2023-04-21 13:17 UTC, Ozaq commented on scripts/read_geometry.py
> +
Please add some high level documentation about what this script is used for.

2023-04-25 09:24 UTC, Ozaq approved these changes

2023-04-25 09:24 UTC, merged